### ISSUE TITLE
license typo in build_requires 

### ISSUE THREAD

**Issue by zhou0** [carandraug/pod-weaver-section-legal-complicated#3]
Running make for C/CD/CDRAUG/Pod-Weaver-Section-Legal-Complicated-1.22.tar.gz
----         Unsatisfied dependencies detected during        ----
---- CDRAUG/Pod-Weaver-Section-Legal-Complicated-1.22.tar.gz ----
    Software::Licence::GPL_3 [build_requires]
    Software::Licence::MIT [build_requires]
    Software::Licence::Perl_5 [build_requires]
Running install for module 'Software::Licence::GPL_3'

  The module Software::Licence::GPL_3 isn't available on CPAN.

  Either the module has not yet been uploaded to CPAN, or it is
  temporary unavailable. Please contact the author to find out
  more about the status. Try 'i Software::Licence::GPL_3'.
Running install for module 'Software::Licence::MIT'

  The module Software::Licence::MIT isn't available on CPAN.

  Either the module has not yet been uploaded to CPAN, or it is
  temporary unavailable. Please contact the author to find out
  more about the status. Try 'i Software::Licence::MIT'.
Running install for module 'Software::Licence::Perl_5'

  The module Software::Licence::Perl_5 isn't available on CPAN.

  Either the module has not yet been uploaded to CPAN, or it is
  temporary unavailable. Please contact the author to find out
  more about the status. Try 'i Software::Licence::Perl_5'.

**Comment by carandraug** [comment]
Now fixed and new release pushed.  Thank you for the bug report and fix.
